language: csharp
jobs:
  include:
    - dotnet: 3.0.100
      mono: none
      env: DOTNETCORE=3
    - mono: latest
      env: MONO=latest
sudo: false  # use the new container-based Travis infrastructure
osx_image: xcode11
os:
  - linux
  - osx
install:
  - if [ "$MONO" == "latest" ]; then 
      nuget src/Vlingo.Symbio.sln
      nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - if [ "$DOTNETCORE" == "3" ]; then 
    dotnet restore ./src/Vlingo.Symbio.sln;
    dotnet build ./src/Vlingo.Symbio.sln;
    dotnet test ./src/Vlingo.Symbio.Tests/Vlingo.Symbio.Tests.csproj;
    else mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Vlingo.Symbio.Tests/bin/Release/Vlingo.Symbio.Tests.dll

notifications:
  slack: vlingo-platform-net:kwiEEBuUpRnz2rYYYstTBpXr