version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macos
  - macos-mojave
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/
before_build:
  - dotnet restore src/Vlingo.Symbio.sln
build:
  project: src/Vlingo.Symbio.sln
  verbosity: minimal
  publish_nuget: true
test_script:
  - dotnet test src/Vlingo.Symbio.Tests
deploy:
  - provider: NuGet
    api_key:
      secure: 174z6giJXgTApy3CkP9a8hwJAmL8uUG6Rtlsf1vwUtlBokZo/S8hJqlF0Pazt0fZ
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true