version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/
before_build:
  - cmd: dotnet restore src/Vlingo.Symbio.sln
build:
  project: src/Vlingo.Symbio.sln
  verbosity: minimal
  publish_nuget: true
test_script:
  - cmd: dotnet test src/Vlingo.Symbio.Tests
deploy:
  - provider: NuGet
    api_key:
      secure: cobGi+AeEbMkeL7gsXmAlC4xLIiiQ+VDDhE/noktJc8TF3oscSzE4V37q8Eeszg1
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master